---
title: "mBATcombo"
output: html_document
date: "2024-10-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1. run mBATcombo for all genes.  
prepare input files.  
```{r}
library(data.table)
library(tidyverse)

# paths
path_gm="./workflow/geneMatrix.tsv.gz"
path_module_genes="./workflow/T5_all_unique_genes.tsv" # all genes expressed in the dataset
outfile_module_gene_list="./7_heritability_enrichment/data/mBATcombo/99_all_DEGtested_genes_100kb.txt"

# read in module gene lists
a <- list.files(path_module_genes, pattern="module_gene_mapping_info_")
files <- paste(path_module_genes,a,sep="")
b <- data_frame(filename=files) %>% 
  mutate(file_contents = map(filename,read_csv)) %>% unnest()
c <- b %>% distinct(accession)

# read in gene matrix for location
geneMx <- fread(path_gm) %>%
  select(ensgid, gene_name, dup_gene_name, hg19g0, g1, g2) %>%
  mutate(Start=as.integer(ifelse(g1-100000<0, 0, g1-100000)),
         End=as.integer(g2+100000))

# merge, extend for 100kb
# format: 
#Chr   Start       End         Gene
#1     19774       19899       Gene1

d <- c %>% left_join(geneMx, by=c("accession"="ensgid")) %>%
  mutate(Chr=as.integer(gsub("chr","",hg19g0))) 
tmp <- d %>% filter(is.na(Chr)==T) # 86 genes on X or Y or not identified in hg19
nrow(tmp)
d <- d %>% filter(is.na(Chr)==F) %>%
  rename(Gene=accession) %>%
  select(Chr, Start, End, Gene)
# output
fwrite(d, file=outfile_module_gene_list)
```
  
run mBATcombo.  
```{sh}
MYBFILE="./workflow/1000G_merged" # 1kg EUR bfiles
MYMA="./workflow/scz2022_rsID_noMHC.ma" # GWAS sumstats with MHC removed (chr6:25000000-34000000)
MYGLIST="./7_heritability_enrichment/data/mBATcombo/99_all_DEGtested_genes_100kb.txt"
MYOUT="./7_heritability_enrichment/data/mBATcombo/02_all_genes_100kb_mBATcombo"

module load gcta

gcta --bfile $MYBFILE --maf 0.01 --mBAT-combo $MYMA --mBAT-gene-list $MYGLIST --mBAT-wind 0 --out $MYOUT --mBAT-print-all-p --thread-num 10

```
  
# 2. hypergeometric test  
Test if mBATcombo significant genes were enriched in the listed GO pathways.  
```{r}
library(data.table)
library(tidyverse)
library(rstatix)

#- read mBATcombo results, calculate FDR to account for multiple-testing
# use DEG-fdr≤0.3 as the background. 

resfile="./7_heritability_enrichment/data/mBATcombo/02_all_genes_100kb_mBATcombo.gene.assoc.mbat"
degpath <- "T5_DEGs_per_cell_type.csv" # read in supplementary Table 5 here.
df.deg <- fread(degpath) %>%
  filter(padj<0.3) %>%
  separate(col=Gene, into=c("Gene_short","ensgid"),sep="_")%>%
  distinct(ensgid) 

f.res <- fread(resfile) %>%
  filter(Gene %in% df.deg$ensgid) %>% 
  select(-FDR_mBATcombo, -if.sig.fdr) %>%
  adjust_pvalue(p.col="P_mBATcombo", output.col="FDR_mBATcombo",method="fdr") %>%
  mutate(if.sig.fdr=ifelse(FDR_mBATcombo<0.05, "yes", "no"))

#- read my gene lists
df.glist <- fread("./workflow/df_GO_BP_ensgid.tsv")
golist <- unique(df.glist$GO_term)

#- dataset for hypergeometric test
#phyper(q, m, n, k, lower.tail = TRUE, log.p = FALSE)
# q vector of quantiles representing the number of white balls drawn
#without replacement from an urn which contains both black and white
#balls.
# m the number of white balls in the urn.
# n the number of black balls in the urn.
# k the number of balls drawn from the urn.
df.res2 <- df.res %>% distinct(Gene, if.sig.fdr) %>% rename(ensgid=Gene)
m=nrow(df.res2 %>% filter(if.sig.fdr=="yes"))
n=nrow(df.res2 %>% filter(if.sig.fdr=="no"))

myout1 <- data.frame(
  GO_term=character(),
  k_nr_genes_sample=numeric(),
  q_nr_mBATcombo_sig_genes_sample=numeric(),
  m_nr_mBATcombo_sig_genes_all=numeric(),
  n_nr_mBATcombo_nonsig_genes_all=numeric(),
  p_hg=numeric()
)
for(i in 1:length(golist)){
  tmp1 <- df.glist %>%
    filter(GO_term==golist[i]) %>%
    inner_join(df.res1,by="ensgid")
  q=nrow(tmp1 %>% filter(if.sig.fdr=="yes"))
  k=nrow(tmp1)
  p=1-phyper(q,m,n,k,lower.tail = TRUE, log.p = FALSE)
  myout1[i,1] <- golist[i]
  myout1[i,2] <- k
  myout1[i,3] <- q
  myout1[i,4] <- m
  myout1[i,5] <- n
  myout1[i,6] <- p
}

myout1 <- myout1 %>% 
  adjust_pvalue(p.col="p_hg", output.col = "fdr_p_hg", method="fdr") %>%
  mutate(pct_qk=q_nr_mBATcombo_sig_genes_sample/k_nr_genes_sample,
         pct_mn=m_nr_mBATcombo_sig_genes_all/(m_nr_mBATcombo_sig_genes_all+n_nr_mBATcombo_nonsig_genes_all)) %>%
  mutate(if.sig.fdr=ifelse(fdr_p_hg<0.05, "yes","no"))

myout1$GO_term <- gsub("_"," ",myout1$GO_term)

# output
outpath <- "./7_heritability_enrichment/output/figS12D/"
fwrite(myout2, file=paste(outpath,"df_01_phyper_mBATenrich_DEG0.3_GO.tsv",sep=""), sep="\t", col.names = T)

```
  
--- end ---  