---
title: "01_fig3F_figS12BC_h2Enrich_DEG_GOterm"
author: Shuyang Yao (shuyang.yao@ki.se)
output: html_document
date: "2025-06-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Aim: examine h2-enrichment in genes on the GO pathways from DEG results. 

# 01. prepare input.   
```{r}
library(data.table)
library(tidyverse)

GOpath <- "./workflow/DEG_GO_terms/" # the files are generated by code in "./5b_differential_gene_expression_analysis/output/Gene_lists_GO_DB/"
outpath <- "./7_heritability_enrichment/data/Pipeline_GO/"
genemxpath <- "./workflow/geneMatrix.tsv.gz"

mypattern="GO_BP_"
myfiles <- list.files(GOpath, pattern = mypattern)
mypattern1 <- paste(GOpath, mypattern,sep="")

genemx0 <- fread(genemxpath) %>%
  mutate(chr=hg19g0,
         start=as.integer(ifelse(((g1-100000)<0),0,(g1-100000))),
         end=as.integer(g2+100000) ) %>%
  filter(chr!="", is.na(g1)==F, is.na(g2)==F) %>%
  select(ensgid, chr, start, end)
d <- data_frame(filename=paste(GOpath,myfiles,sep="")) %>% 
  mutate(file_contents = map(filename,read_tsv,col_names=F)) %>%
  unnest() %>%
  mutate(GO_term=gsub(mypattern1,"",filename)) %>%
  mutate(GO_term=gsub("_ensgids.csv","",GO_term)) %>%
  mutate(GO_term=gsub(" ","_",GO_term)) %>%
  mutate(GO_term=gsub(",","_",GO_term)) %>%
  mutate(GO_term=gsub("-","_",GO_term)) %>%
  select(X1,GO_term) %>%
  rename(ensgid=X1)
unique(d$GO_term)

e <- d %>% inner_join(genemx0,by=c("ensgid")) 

fwrite(d, file=paste(GOpath,"df_GO_BP_ensgid.tsv",sep=""),
       sep="\t", col.names = T)

# output, one bed file per unique GO_term
ldsc_bedfile <- function(d,GO_term){
  d_spe <- d %>% group_by(GO_term) 
  d_spe %>% do(write_group(.,GO_term))
}
write_group  = function(df,GO_term) {
  df <- select(df,GO_term,chr,start,end,ensgid)
  dir.create(paste0("Bed"), showWarnings = FALSE,recursive = TRUE)
  write_tsv(df[-1],paste0("Bed/",make.names(unique(df[1])),".bed"),col_names = F)
  return(df)
}
setwd(outpath)
# rm existing bed files
system("rm Bed/*.bed")
e %>% ldsc_bedfile(GO_term)

```
  
# 02. run LDSC  
```{bash}
SCRIPTS_DIR=./7_heritability_enrichment/scripts
PIPELINE=Pipeline_GO
MAIN_DIR=./7_heritability_enrichment/data

cd ${MAIN_DIR}/${PIPELINE}

#- 1. calculate LD
sbatch -o ${MAIN_DIR}/${PIPELINE}/LOG_01a_LDSC_calculate_LD.log \
    -n 1 -t 01:00:00 --mem=16g \
    ${SCRIPTS_DIR}/01a_pLDSC_calculate_LD.sh ${PIPELINE}

#- 2. partition heritability (run when step 1 finishes)
sbatch -o ${MAIN_DIR}/${PIPELINE}/LOG_01b_LDSC_partition_h2.log \
    -n 1 -t 01:00:00 --mem=16g \
    ${SCRIPTS_DIR}/01b_pLDSC_partition_h2.sh ${PIPELINE}

```
  
# 03. Process results  
```{r}
library(data.table)
library(tidyverse)
library(rstatix)
library(ggplot2)

indir <- "./7_heritability_enrichment/data/"
outdir <- "./7_heritability_enrichment/output/fig3F/"

myfiles <- list.files(indir)

a <- data.frame(filenames=paste(indir,myfiles,sep=""),
                filenames1=myfiles) %>%
  mutate(conent= map(filenames, read_tsv)) %>%
  unnest() %>%
  filter(Category=="L2_1") %>%
  separate(col=filenames1,into=c("Trait","annot"),sep="_other_SUN_DEG_GO-") %>%
  mutate(annot=gsub("\\.results","",annot)) %>%
  select(-filenames,-Category)

a$annot <- gsub("__"," ", a$annot)
a$annot <- gsub("_"," ", a$annot)

b <- a %>% filter(`Prop._SNPs`>=0.01) %>% # remove annotations that are too small
  adjust_pvalue(p.col="Enrichment_p", output.col="Enrichment_fdr", method="fdr") %>%
  mutate(if.sig.fdr = ifelse(Enrichment_fdr<=0.05,"yes","no")) %>% 
  arrange(Enrichment_p)
b$annot <- gsub("_"," ", b$annot)

 
fwrite(a %>% select(annot,`Prop._SNPs`),
       file=paste(outdir,"01_annot_size.tsv",sep=""), 
       sep="\t", col.names=T)
fwrite(b,
       file=paste(outdir,"02_LDSC_res_DEG_GO_terms_size0.01.tsv",sep=""), 
       sep="\t", col.names=T)

```
  
-- end --  