---
title: "02_LDSC_regulon_targets"
output: html_document
date: "2025-07-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
  
1. make bed files  
- pre-process regulon output.
- read in gene matrix.  
- get hg19 coordinates per target.  
- convert to .bed format.  
2. run partitioned LDSC regression  
  
```{r}
# extract all target gene lists per significant celltype-regulon combination (n=19)

library(data.table)
library(tidyverse)

DIR1 <- "./workflow/"
path1.regulon <- paste(DIR1,"median_regulon_AUC_donor_celltype_sign.csv",sep="")
path1.raw.dir <- paste(DIR1,"regulon_files/",sep="")

# read regulon file
b.regulon <- fread(path1.regulon) %>% distinct(celltype, regulon)

a.files <- list.files(path1.raw.dir)
c_regulon_targets <- NULL
for(i in 1:length(a.files)){
  # loop over cell type files (with all TF-target pairs),
  filei <- fread(paste(path1.raw.dir,a.files[i],sep=""))
  # grep cell type name
  cti <- gsub("all_","", a.files[i])
  cti <- gsub("_adj.csv","", cti)
  # grep all regulon matched with the cell type
  regulon_i <- b.regulon %>% 
    filter(celltype==cti) %>% 
    distinct(celltype, regulon) %>%
    mutate(regulon=sub("\\(.*$", "", regulon))
  # filter TF==regulon from all TF-target pairs
  df_i <- filei %>% filter(TF%in%regulon_i$regulon) %>%
    distinct(TF, target) %>%
    mutate(celltype=cti) # add column of celltypes
  # rbind to final dataset
  c_regulon_targets <- rbind(c_regulon_targets, df_i)
}

# output
setwd(DIR1)
fwrite(c_regulon_targets %>% arrange(celltype, TF, target),
       file="02_processed_cell_regulon_targets.tsv",
       sep="\t", col.names = T)

```
  
bed files  
```{r}
library(data.table)
library(tidyverse)

DIR1 <- "./workflow/"
path1.regulon <- paste(DIR1, "02_processed_cell_regulon_targets.tsv",sep="")
path1.genemx <- paste(DIR1, "geneMatrix.tsv.gz",sep="") 
DIR2 <- "./7_heritability_enrichment/data/"

c_regulon_targets <- fread(path1.regulon) 

geneMx <- fread(path1.genemx) %>%
  filter(PAR=="FALSE",
         !hg19g0%in%c("chrX","chrY","chrM",""),
         is.na(hg19g0)==F,
         is.na(g1)==F,
         is.na(g2)==F) %>%
  mutate(chr=hg19g0,
         start=as.integer(ifelse(((g1-100000)<0),0,(g1-100000))),
         end=as.integer(g2+100000) ) %>%
  distinct(gene_name, chr, start, end) %>% 
  group_by(gene_name) %>%
  slice(1) %>%
  ungroup()

d <- c_regulon_targets %>%
  left_join(geneMx, by=c("target"="gene_name")) %>%
  filter(is.na(chr)==F)

# loop over cell type-regulon combinations
tmp <- d %>% distinct(celltype, TF)
for(i in 1:nrow(tmp)){
  # get cell type and TF
  cti <- as.character(tmp[i,"celltype"])
  tfi <- as.character(tmp[i,"TF"])
  # get data frame to output (in bed format)
  dfi <- d %>% 
    filter(celltype==cti, TF==tfi) %>%
    select(chr, start, end) %>%
    arrange(chr, start, end)
  # prepare file name
  namei <- paste(cti,tfi,sep="_")
  outi <- paste(DIR1,"bed/",namei,".bed",sep="")
  # output
  if(file.exists(outi)==T){
    system(paste("rm ",outi,sep=""))
    fwrite(dfi, outi, sep="\t", col.names = F)
  }else{
    fwrite(dfi, outi, sep="\t", col.names = F)
  }
}
# check number of targets per celltype-TF:
e <- d %>% group_by(celltype, TF) %>% summarise(n=n())
fwrite(e, file=paste(DIR2, "99_sig_regulon_N_target.tsv",sep=""),
       sep="\t", col.names = T)
```
  
partitioned LDSC  
```{bash, eval=F}
SCRIPTS_DIR=./7_heritability_enrichment/scripts
PIPELINE=Regulon
MAIN_DIR=./7_heritability_enrichment/data

cd ${MAIN_DIR}/${PIPELINE}

#- 1. calculate LD
sbatch -o ${MAIN_DIR}/${PIPELINE}/LOG_01a_LDSC_calculate_LD.log \
    -n 1 -t 01:00:00 --mem=16g \
    ${SCRIPTS_DIR}/01a_pLDSC_calculate_LD.sh ${PIPELINE}

#- 2. partition heritability (run when step 1 finishes)
sbatch -o ${MAIN_DIR}/${PIPELINE}/LOG_01b_LDSC_partition_h2.log \
    -n 1 -t 01:00:00 --mem=16g \
    ${SCRIPTS_DIR}/01b_pLDSC_partition_h2.sh ${PIPELINE}

```
  
3. Tidy up results  
```{r}
library(tidyverse)
library(data.table)
library(rstatix)
library(readxl)

inpath <- "./7_heritability_enrichment/data/"
outpath <- "./7_heritability_enrichment/output/fig22B/"

myfun.ldsc <- function(a){
  files <- list.files(a,pattern=".results",full.names = TRUE)
  d <- data_frame(filename=files) %>% mutate(file_contents = map(filename,read_tsv)) %>%
    mutate(V1=gsub("scz2022_other_SUN_DEG_GO-","",basename(filename))
    ) %>% unnest() %>%
    filter(Category=="L2_1") %>% #mutate(P=1-pnorm(`Coefficient_z-score`)) %>% 
    mutate(V1=gsub("\\.results","",V1),
           Trait="scz2022") %>%
    select(Trait,everything())
  return(d)
}

#- format and account for multiple-testing within each decile across cell types
mydf1 <- myfun.ldsc(inpath) %>%
  select(-filename, -Category) %>%
  adjust_pvalue(p.col="Enrichment_p", output.col="FDR", method="fdr") %>%
  mutate(if.sig.fdr=ifelse(FDR<=0.05, "yes","no")) %>%
  select(V1, FDR, if.sig.fdr, everything()) 

#- output
fwrite(mydf1,
       file=paste(outpath,"df_pLDSC_regulon.tsv",sep=""),
       sep="\t", col.names = T)
```
  
--- end ---  